name: Keep Supabase Alive

on:
  schedule:
    # Runs at 09:00 UTC every 3 days
    - cron: '0 9 */3 * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase via PostgREST (HEAD request)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          # Change this to a lightweight table in your project if needed
          SUPABASE_TABLE: rooms
        run: |
          set -e
          echo "Pinging ${SUPABASE_URL}/rest/v1/${SUPABASE_TABLE} ..."
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            -X GET "${SUPABASE_URL}/rest/v1/${SUPABASE_TABLE}?select=id&limit=1" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Range: 0-0" \
            -H "Prefer: count=exact")
          echo "HTTP ${STATUS_CODE}"
          # Treat any non-2xx/3xx as failure
          if [ "${STATUS_CODE}" -lt 200 ] || [ "${STATUS_CODE}" -ge 400 ]; then
            echo "Ping failed with status ${STATUS_CODE}." >&2
            exit 1
          fi
          echo "Ping successful."


